- name: Remove sudo access for zuul user.
  become: yes
  file:
    path: /etc/sudoers.d/zuul
    state: absent

- name: Prove that general sudo access is actually revoked.
  shell: '! sudo -n true'
  tags:
    # We really need shell above, skip warning
    - skip_ansible_lint
