- name: Require tox_envlist variable
  fail:
    msg: tox_envlist is required for this role
  when: tox_envlist is not defined

- name: Run tox without tests
  command: "{{ tox_executable }} --notest -e{{ tox_envlist }}"
  args:
    chdir: "{{ zuul_work_dir }}"
  when: tox_install_siblings

# TODO(mordred) handle tox_envlist being a list
# NOTE(jeblair) disabled because of lack of constraints support
#- name: Install any sibling python packages
#  tox_install_sibling_packages:
#    tox_envlist: "{{ tox_envlist }}"
#    project_dir: "{{ zuul_work_dir }}"
#    projects: "{{ zuul.projects | selectattr('required') | list }}"
#  when: tox_install_siblings
